pipeline {
    agent {
        docker {
            image 'jenkins/inbound-agent-terraform:1.14'
        }
    }

    environment {
        TF_IN_AUTOMATION = "true"
        TF_INPUT = "false"
        AWS_DEFAULT_REGION = "ap-southeast-2"
    }

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Format') {
            steps {
                sh 'terraform fmt -check -recursive'
            }
        }

        stage('Terraform Security Scan') {
            steps {
                sh '''
                  if command -v tfsec >/dev/null 2>&1; then
                    tfsec . \
                    --exclude-path terraform/inspect
                  else
                    echo "tfsec not installed, skipping security scan"
                  fi
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'aws-prod']
                ]) {
                    sh '''
                      terraform -chdir=terraform/env/prod init -input=false
                    '''
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                sh 'terraform -chdir=terraform/env/prod validate'
            }
        }
    
        stage('Terraform Plan') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'aws-prod']
                ]) {
                    sh '''
                      terraform -chdir=terraform/env/prod plan -var-file=$(pwd)/terraform/env/prod/terraform.tfvars -no-color -out=tfplan
                      terraform -chdir=terraform/env/prod show -no-color tfplan > tfplan.txt
                    '''
                }
            }
        }

        stage('Comment PR with Terraform Plan') {
            when {
                expression { env.CHANGE_ID != null }
            }
            steps {
                withCredentials([
                    string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')
                ]) {
                    sh '''
                        set -e

                        echo "Commenting on PR #$CHANGE_ID"

                        COMMENT_BODY=$(cat <<-EOF
                        ### 🧱 Terraform Plan Result

                        \`\`\`
                        $(sed -e 's/`/\\`/g' tfplan.txt)
                        \`\`\`

                        ✅ Generated by Jenkins CI
                        EOF
                        )

                        gh pr comment "$CHANGE_ID" \
                        --repo "$GIT_URL" \
                        --body "$COMMENT_BODY"
                    '''
                }
            }
        }

        stage('Approve Apply') {
            when {
                branch 'main'
            }
            steps {
                input message: 'Apply Terraform to production?'
            }
        }

        stage('Terraform Apply') {
            when {
                branch 'main'
            }
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'aws-prod']
                ]) {
                    sh 'terraform -chdir=terraform/env/prod apply -auto-approve tfplan'
                }
            }
        }
    }

    post {
        success {
            echo 'Terraform pipeline passed ✅'
        }
        failure {
            echo 'Terraform pipeline failed ❌'
        }
        always {
            archiveArtifacts artifacts: 'tfplan,tfplan.txt', onlyIfSuccessful: false
        }
    }
}